#!/usr/bin/env bash
args=("$@")
index=0
for i in "$@"; do
    if [ "$i" == "-d" ]; then
        unset 'args[$index]'
        unset 'args[$index+1]'
    fi
    index=$((index + 1))
done

/home/dusza/larawhale/frankenphp php-cli ${args[@]}
