name: Deploy projekt_neve_itt to production server
on: "workflow_dispatch"
jobs:
  deploy-to-prod:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v3
      - name: Pull latest draft release
        id: pull_latest_draft_release
        uses: actions/github-script@v7
        with:
          script: |
            const { data: releases } = await github.repos.listReleases({
              owner: context.repo.owner,
              repo: context.repo.repo,
              per_page: 1,
              draft: true,
              latest: true
            });
            github.repos.downloadReleaseAsset({
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: releases[0].id,
              asset_id: releases[0].assets[0].id,
              output_file: 'ci/larawhale_linux-x86_64'
            });

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          known_hosts: "just-a-placeholder-so-we-dont-get-errors"
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
      - name: Deploy with rsync
        run: rsync -avz --ignore-errors ./ci ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/home/dusza/larawhale
      - name: Run deploy script on server
        if: success() || failure()
        run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "bash /opt/larawhale/deploy.sh"
