name: Deploy projekt_neve_itt to production server
on:
  workflow_run:
    workflows: ["Build projekt_neve_itt Docker image"]
    branches: [main]
    types:
      - completed
jobs:
  deploy-to-prod:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v3
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          known_hosts: "just-a-placeholder-so-we-dont-get-errors"
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
      - name: Deploy with rsync
        run: rsync -avz --ignore-errors ./ci ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/opt/larawhale
      - name: Run deploy script on server
        if: success() || failure()
        run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "bash /opt/larawhale/deploy.sh"
